"""
Django settings for hotel_config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-r%gqz*9ub!bvvk_g&)9*za7mzurxta3+f+h_w^wu+y#1qi2^+t",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to off; enable locally with DEBUG=1.
DEBUG = os.environ.get("DEBUG", "").lower() in ("1", "true", "yes")

# Hosts: always allow Vercel domains and localhost; extend via ALLOWED_HOSTS env.
ALLOWED_HOSTS = [".vercel.app", ".now.sh", "localhost", "127.0.0.1"]
if os.environ.get("ALLOWED_HOSTS"):
    ALLOWED_HOSTS += [h.strip() for h in os.environ["ALLOWED_HOSTS"].split(",") if h.strip()]
if os.environ.get("VERCEL_URL"):
    ALLOWED_HOSTS.append(os.environ["VERCEL_URL"])

# CSRF: trust the deployed Vercel origin(s).
CSRF_TRUSTED_ORIGINS = ["https://*.vercel.app"]
if os.environ.get("VERCEL_URL"):
    CSRF_TRUSTED_ORIGINS.append("https://" + os.environ["VERCEL_URL"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "rooms",
    "bookings",
    "payments",
    "reviews",
    "dashboards",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hotel_config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hotel_config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Uses DATABASE_URL / POSTGRES_URL (Supabase) in production, SQLite locally.

import dj_database_url  # noqa: E402

_db_url = os.environ.get("DATABASE_URL") or os.environ.get("POSTGRES_URL")
if _db_url:
    _db = dj_database_url.parse(_db_url, conn_max_age=0)
    # Supabase's pooled URL carries non-standard query params (e.g. pgbouncer,
    # supa) that psycopg2 rejects — keep only sslmode.
    _opts = _db.get("OPTIONS", {})
    _db["OPTIONS"] = {"sslmode": _opts.get("sslmode", "require")}
    # Required when connecting through the Supabase transaction pooler (pgbouncer).
    _db["DISABLE_SERVER_SIDE_CURSORS"] = True
    DATABASES = {"default": _db}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# build_files.sh runs collectstatic into staticfiles_build/static, which Vercel
# serves from /static/ (see vercel.json).

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles_build" / "static"

# Media files (uploaded room images) are stored in Vercel Blob in production
# (serverless filesystem is ephemeral); fall back to local disk for development.
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STORAGES = {
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
if os.environ.get("BLOB_READ_WRITE_TOKEN"):
    STORAGES["default"] = {"BACKEND": "hotel_config.storage.VercelBlobStorage"}
else:
    STORAGES["default"] = {"BACKEND": "django.core.files.storage.FileSystemStorage"}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication redirects
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"

# Map the messages framework's ERROR level to Bootstrap's "danger" class
from django.contrib.messages import constants as message_constants  # noqa: E402

MESSAGE_TAGS = {
    message_constants.ERROR: "danger",
}

# Production security: Vercel terminates TLS at the edge and forwards via proxy.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
